# Data Profiling

In [35]:

!pip install pandas 
import pandas as pd

Requirement already satisfied: pandas in d:\DEPI\.venv\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in d:\DEPI\.venv\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\DEPI\.venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\DEPI\.venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\DEPI\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [36]:
df = pd.read_csv("SuperMarket.csv")
df.head(25)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.22,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,NaN,10:37:00 AM,E-wallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,NaN,6:30:00 PM,E-wallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.692,NaN,2:36:00 PM,E-wallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.38,NaN,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.146,NaN,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.746,NaN,1:27:00 PM,Credit card,164.52,4.761905,8.2260,5.9
10,351-62-0822,Cairo,Mandalay,Member,Female,Fashion accessories,14.48,4,2.8960,60.816,NaN,6:07:00 PM,Ewallet,57.92,4.761905,2.8960,4.5
11,529-56-3974,Cairo,Mandalay,Member,Female,Electronic accessories,25.51,4,5.1020,107.142,NaN,5:03:00 PM,Cash,102.04,4.761905,5.1020,6.8
12,365-64-0515,Alex,Yangon,Member,Female,Electronic accessories,46.95,5,11.7375,246.4875,NaN,10:25:00 AM,Ewallet,234.75,4.761905,11.7375,7.1
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.5950,453.495,NaN,4:48:00 PM,E-wallet,431.90,4.761905,21.5950,8.2
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.49,NaN,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
15,299-46-1805,Cairo,Mandalay,Member,Female,Sports and travel,93.72,6,28.1160,590.436,NaN,4:19:00 PM,Cash,562.32,4.761905,28.1160,4.5
16,656-95-9349,Alex,Yangon,Member,Female,Health and beauty,68.93,7,24.1255,506.6355,3/11/2019,11:03:00 AM,Credit card,482.51,4.761905,24.1255,4.6
17,765-26-6951,Alex,Yangon,Member,Female,Sports and travel,72.61,6,21.7830,457.443,1/1/2019,10:39:00 AM,Credit card,435.66,4.761905,21.7830,6.9
18,329-62-1586,Alex,Yangon,Member,Female,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,6:00:00 PM,Credit card,164.01,4.761905,8.2005,8.6
19,319-50-3348,Cairo,Mandalay,Member,Female,Home and lifestyle,40.30,2,4.0300,84.63,3/11/2019,3:30:00 PM,Ewallet,80.60,4.761905,4.0300,4.4
20,300-71-4605,Giza,Naypyitaw,Member,Female,Electronic accessories,86.04,5,21.5100,451.71,2/25/2019,11:24:00 AM,Ewallet,430.20,4.761905,21.5100,4.8
21,371-85-5789,Cairo,Mandalay,Member,Female,Health and beauty,87.98,3,13.1970,277.137,3/5/2019,10:40:00 AM,Ewallet,263.94,4.761905,13.1970,5.1
22,273-16-6619,Cairo,Mandalay,Member,Female,Home and lifestyle,33.20,2,3.3200,69.72,3/15/2019,12:20:00 PM,Credit card,66.40,4.761905,3.3200,4.4
23,636-48-8204,Alex,Yangon,Member,Female,Electronic accessories,34.56,5,8.6400,181.44,2/17/2019,11:15:00 AM,Ewallet,172.80,4.761905,8.6400,9.9
24,549-59-1358,Alex,Yangon,Member,Female,Sports and travel,88.63,3,13.2945,279.1845,3/2/2019,5:36:00 PM,Ewallet,265.89,4.761905,13.2945,6.0

In [37]:
# 1- Column names and types 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1014 non-null   str
 1   Branch                   1014 non-null   str
 2   City                     1014 non-null   str
 3      Customer type         1014 non-null   str
 4   Gender                   1014 non-null   str
 5   Product line             1014 non-null   str
 6   Unit price               990 non-null    float64
 7   Quantity                 1014 non-null   int64
 8   Tax 5%                   1014 non-null   float64
 9   Sales                    994 non-null    str
 10  Date                     1002 non-null   str
 11  Time                     1014 non-null   str
 12  Payment                  1014 non-null   str
 13     cogs                  1014 non-null   float64
 14  gross margin percentage  1014 non-null   float64
 15  gross income             1014 non-null   float64
 16  Rating                   1014 non-null   float64
dtypes: float64(6), int64(1), str(10)
memory usage: 134.8 KB

In [38]:
# 2- Number of null values in each column 
df.isna().sum()

Invoice ID                  0
Branch                      0
City                        0
   Customer type            0
Gender                      0
Product line                0
Unit price                 24
Quantity                    0
Tax 5%                      0
Sales                      20
Date                       12
Time                        0
Payment                     0
   cogs                     0
gross margin percentage     0
gross income                0
Rating                      0
dtype: int64

In [39]:
# 3- Number of duplicate rows 
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1009     True
1010     True
1011     True
1012     True
1013     True
Length: 1014, dtype: bool

In [40]:
# 4- Basic statistical information 
df.describe()

,Unit price,Quantity,Tax 5%,cogs,gross margin percentage,gross income,Rating
count,990.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000,1014.000000
mean,55.520333,5.502959,15.336872,306.737436,4.761905,15.336872,6.960454
std,26.330508,2.927133,11.685945,233.718896,0.000000,11.685945,1.721264
min,10.080000,1.000000,0.508500,10.170000,4.761905,0.508500,4.000000
25%,33.202500,3.000000,5.864625,117.292500,4.761905,5.864625,5.500000
50%,54.890000,5.000000,12.066000,241.320000,4.761905,12.066000,6.900000
75%,77.667500,8.000000,22.428000,448.560000,4.761905,22.428000,8.475000
max,99.960000,10.000000,49.650000,993.000000,4.761905,49.650000,10.000000

In [41]:
df['   Customer type'].value_counts()

   Customer type
Member    570
Normal    444
Name: count, dtype: int64

In [42]:
df['Branch'].value_counts()

Branch
Alex                  341
Giza                  330
Cairo                 330
     Cairo              7
Alex                    3
giza                    1
cairo                   1
      Cairo             1
Name: count, dtype: int64

In [43]:
df['Gender'].value_counts()

Gender
Female    566
Male      426
F          13
M           9
Name: count, dtype: int64

In [44]:
df['Payment    '].value_counts()

Payment
Ewallet        351
Cash           338
Credit card    309
cash             7
credit card      5
E-wallet         4
Name: count, dtype: int64

In [45]:
df['Product line'].value_counts()

Product line
Fashion accessories       181
Food and beverages        177
Electronic accessories    172
Sports and travel         168
Home and lifestyle        160
Health and beauty         156
Name: count, dtype: int64

In [46]:
df['City'].value_counts()

City
Yangon       344
Mandalay     339
Naypyitaw    331
Name: count, dtype: int64

In [47]:
# 5- Suspicious and unnData 
"""
There are a lot of data with different alliases like Male and M in, Female and F df['Gender']
Ewallet and E-wallet, cash and Cash in df['payment']
Multiple Cairo values in df['Branch']
The City column is unnecessary 
"""

"\nThere are a lot of data with different alliases like Male and M in, Female and F df['Gender']\nEwallet and E-wallet, cash and Cash in df['payment']\nMultiple Cairo values in df['Branch']\nThe City column is unnecessary \n"

In [48]:
#6 Observations
"""
I observed that some columns has null values, each of which most of them I can't just take the average or plug random
values so I will replace NaN with "Unknown" in those columns.

I observed that some columns have weird names with a lot of whitespace which I will fix by renaming. 

I observed the numerical values were fine and doesn't need any numerical handling.

I also observed that the date and time are not datetime objects

Finally some rows were duplicates which I will delete. 

"""

'\nI observed that some columns has null values, each of which most of them I can\'t just take the average or plug random\nvalues so I will replace NaN with "Unknown" in those columns.\n\nI observed that some columns have weird names with a lot of whitespace which I will fix by renaming. \n\nI observed the numerical values were fine and doesn\'t need any numerical handling.\n\nI also observed that the date and time are not datetime objects\n\nFinally some rows were duplicates which I will delete. \n\n'

# Data Cleaning

In [49]:
# 1- Renaming
df.rename(columns={'   Customer type':'Customer Type','   cogs':'COGS','Payment    ':'Payment Type','Unit price':'Unit Price',
                   'gross income':'Gross Income','gross margin percentage':'Gross Margin Percentage'},inplace=True) 
df.head(0)

Empty DataFrame
Columns: [Invoice ID, Branch, City, Customer Type, Gender, Product line, Unit Price, Quantity, Tax 5%, Sales, Date, Time, Payment Type, COGS, Gross Margin Percentage, Gross Income, Rating]
Index: []

In [50]:
# 2- Handling missing values (Unit Price, Sales, and Date)

df['Date'] = df['Date'].fillna('Unknown')

df['Unit Price'] = df['Unit Price'].fillna(0.0)

df['Sales'] = pd.to_numeric(df['Sales'], errors='coerce')
df['Sales'] = df['Sales'].fillna(0.0)
        
        
df.isna().sum()

Invoice ID                 0
Branch                     0
City                       0
Customer Type              0
Gender                     0
Product line               0
Unit Price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment Type               0
COGS                       0
Gross Margin Percentage    0
Gross Income               0
Rating                     0
dtype: int64

In [51]:
# 3- Duplicate rows removal
df = df.drop_duplicates()
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [52]:
# 4- Unnecessary Rows Removal
None

In [53]:
# 5- Correct Data and Datatypes
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   str
 1   Branch                   1000 non-null   str
 2   City                     1000 non-null   str
 3   Customer Type            1000 non-null   str
 4   Gender                   1000 non-null   str
 5   Product line             1000 non-null   str
 6   Unit Price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   str
 11  Time                     1000 non-null   str
 12  Payment Type             1000 non-null   str
 13  COGS                     1000 non-null   float64
 14  Gross Margin Percentage  1000 non-null   float64
 15  Gross Income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), str(9)
memory usage: 132.9 KB

In [54]:
df['Date'] = pd.to_datetime(df['Date'], format='%m/%d/%Y', errors='coerce')
df['Time'] = pd.to_datetime(df['Time'], format='%I:%M:%S %p')

In [55]:
for i,value in enumerate(df['Gender']):
    if value == 'M':
        df.loc[i,'Gender'] = 'Male'
    elif value == 'F':
        df.loc[i,'Gender'] = 'Female'
        
df['Gender'].value_counts()

Gender
Female    571
Male      429
Name: count, dtype: int64

In [56]:
df['Branch']=df['Branch'].str.strip()
for i,value in enumerate(df['Branch']):
    if value == 'giza':
        df.loc[i,'Branch'] = 'Giza'
    elif value == 'cairo':
        df.loc[i,'Branch'] = 'Cairo'
        
df['Branch'].value_counts()

Branch
Alex     340
Cairo    332
Giza     328
Name: count, dtype: int64

In [57]:
for i,value in enumerate(df['Payment Type']):
    if value == 'cash':
        df.loc[i,'Payment Type'] = 'Cash'
    elif value == 'credit card':
        df.loc[i,'Payment Type'] = 'Credit card'
    elif value == 'Ewallet': 
        df.loc[i,'Payment Type'] = 'E-wallet'
df['Payment Type'].value_counts()

Payment Type
E-wallet       345
Cash           344
Credit card    311
Name: count, dtype: int64

In [58]:
# 6- Sorting according to date and time
df = df.sort_values(by=['Date', 'Time'], ascending=[False, True])

In [59]:
# 7- New day month and year columns 
df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.strftime('%b')
df['Year'] = df['Date'].dt.year

df = df.drop(columns=['Date'])
df.head(5)

,Invoice ID,Branch,City,Customer Type,Gender,Product line,Unit Price,Quantity,Tax 5%,Sales,Time,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating,Day,Month,Year
937,361-85-2571,Alex,Yangon,Normal,Female,Sports and travel,89.48,5,22.3700,469.7700,1900-01-01 10:18:00,Cash,447.40,4.761905,22.3700,7.4,30.0,Mar,2019.0
883,291-55-6563,Alex,Yangon,Member,Female,Home and lifestyle,34.42,6,10.3260,216.8460,1900-01-01 12:45:00,E-wallet,206.52,4.761905,10.3260,7.5,30.0,Mar,2019.0
881,115-38-7388,Giza,Naypyitaw,Member,Female,Fashion accessories,10.18,8,4.0720,85.5120,1900-01-01 12:51:00,Credit card,81.44,4.761905,4.0720,9.5,30.0,Mar,2019.0
306,286-01-5402,Alex,Yangon,Normal,Female,Sports and travel,40.23,7,14.0805,295.6905,1900-01-01 13:22:00,Cash,281.61,4.761905,14.0805,9.6,30.0,Mar,2019.0
158,743-04-1105,Cairo,Mandalay,Member,Male,Health and beauty,97.22,9,43.7490,918.7290,1900-01-01 14:43:00,E-wallet,874.98,4.761905,43.7490,6.0,30.0,Mar,2019.0

In [60]:
df['Time'] = pd.to_datetime(
    df['Time'],
    format='%I:%M:%S %p'
).dt.time

In [61]:
# 8- Satisfied column
df['Satisfied'] = df['Rating']>=7
df.head(10)

,Invoice ID,Branch,City,Customer Type,Gender,Product line,Unit Price,Quantity,Tax 5%,Sales,Time,Payment Type,COGS,Gross Margin Percentage,Gross Income,Rating,Day,Month,Year,Satisfied
937,361-85-2571,Alex,Yangon,Normal,Female,Sports and travel,89.48,5,22.3700,469.7700,10:18:00,Cash,447.40,4.761905,22.3700,7.4,30.0,Mar,2019.0,True
883,291-55-6563,Alex,Yangon,Member,Female,Home and lifestyle,34.42,6,10.3260,216.8460,12:45:00,E-wallet,206.52,4.761905,10.3260,7.5,30.0,Mar,2019.0,True
881,115-38-7388,Giza,Naypyitaw,Member,Female,Fashion accessories,10.18,8,4.0720,85.5120,12:51:00,Credit card,81.44,4.761905,4.0720,9.5,30.0,Mar,2019.0,True
306,286-01-5402,Alex,Yangon,Normal,Female,Sports and travel,40.23,7,14.0805,295.6905,13:22:00,Cash,281.61,4.761905,14.0805,9.6,30.0,Mar,2019.0,True
158,743-04-1105,Cairo,Mandalay,Member,Male,Health and beauty,97.22,9,43.7490,918.7290,14:43:00,E-wallet,874.98,4.761905,43.7490,6.0,30.0,Mar,2019.0,False
646,778-89-7974,Giza,Naypyitaw,Normal,Male,Health and beauty,70.21,6,21.0630,442.3230,14:58:00,Cash,421.26,4.761905,21.0630,7.4,30.0,Mar,2019.0,True
671,642-61-4706,Cairo,Mandalay,Member,Male,Food and beverages,93.40,2,9.3400,196.1400,16:34:00,Cash,186.80,4.761905,9.3400,5.5,30.0,Mar,2019.0,False
474,676-39-6028,Alex,Yangon,Member,Female,Electronic accessories,64.44,5,16.1100,338.3100,17:04:00,Cash,322.20,4.761905,16.1100,6.6,30.0,Mar,2019.0,False
473,731-59-7531,Cairo,Mandalay,Member,Male,Health and beauty,72.57,8,29.0280,609.5880,17:58:00,Cash,580.56,4.761905,29.0280,4.6,30.0,Mar,2019.0,False
643,131-15-8856,Giza,Naypyitaw,Member,Female,Food and beverages,72.52,8,29.0080,609.1680,19:26:00,Credit card,580.16,4.761905,29.0080,4.0,30.0,Mar,2019.0,False

# Data Analysis

In [29]:
# 1- Total Revenue 
totalRevenue = df['Sales'].sum()
totalRevenue

np.float64(311490.039)

In [62]:
# 2- Total revenue by city and rank them 
cityRevenue = df.groupby('City')['Sales'].sum()
cityRevenue

City
Mandalay     103147.7265
Naypyitaw    105900.1545
Yangon       102442.1580
Name: Sales, dtype: float64

In [63]:
cityRevenue.sort_values(ascending=False)

City
Naypyitaw    105900.1545
Mandalay     103147.7265
Yangon       102442.1580
Name: Sales, dtype: float64

In [ ]:
# 3- Total profit by branch and rank them
totalProfitBranch = df.groupby('Branch')['Gross Income'].sum()
totalProfitBranch

Branch
Alex     5057.1605
Cairo    5057.0320
Giza     5265.1765
Name: Gross Income, dtype: float64

In [66]:
totalProfitBranch.sort_values(ascending=False)

Branch
Giza     5265.1765
Alex     5057.1605
Cairo    5057.0320
Name: Gross Income, dtype: float64

In [67]:
# 4- Total profit and revenue by category 
productCategoryAnalysis = df.groupby('Product line').agg(Revenue = ('Sales','sum'), Profit = ('Gross Income','sum'))
productCategoryAnalysis

                           Revenue     Profit
Product line
Electronic accessories  52545.7590  2587.5015
Fashion accessories     52245.2490  2585.9950
Food and beverages      54886.3035  2673.5640
Health and beauty       46849.9500  2342.5590
Home and lifestyle      51431.3835  2564.8530
Sports and travel       53531.3940  2624.8965

In [ ]:
productCategoryAnalysis.sort_values(by=['Revenue','Profit'], ascending=[False,False])
# Food is the top performing category

                           Revenue     Profit
Product line
Food and beverages      54886.3035  2673.5640
Sports and travel       53531.3940  2624.8965
Electronic accessories  52545.7590  2587.5015
Fashion accessories     52245.2490  2585.9950
Home and lifestyle      51431.3835  2564.8530
Health and beauty       46849.9500  2342.5590

In [ ]:
# 5- Total spending by costumer type 
costumerSpendings = df.groupby('Customer Type')['Sales'].sum().sort_values(ascending=False)
costumerSpendings
# A member spends more money

Customer Type
Member    178218.054
Normal    133271.985
Name: Sales, dtype: float64

In [ ]:
# 6- Number of transactions by payment method 
df['Payment Type'].value_counts().sort_values(ascending=False)
# E-wallet is the most popular

Payment Type
E-wallet       345
Cash           344
Credit card    311
Name: count, dtype: int64

In [76]:
# 7- The average transaction value of the supermarket 
df['Sales'].mean()

np.float64(311.49003899999997)

In [ ]:
# 8- Satisfaction rate by branch 
satisfactionByBranch = df.groupby('Branch').agg(AverageSatisfaction = ('Satisfied','mean'), AverageRating = ('Rating','mean'))
satisfactionByBranch
# Alex branch is the winner winner chicken dinner

        AverageSatisfaction  AverageRating
Branch
Alex               0.526471       7.027059
Cairo              0.454819       6.818072
Giza               0.521341       7.072866

In [89]:
# 9- Total revenue by month and day
totalRevenueMonth = df.groupby('Month')['Sales'].sum().sort_values(ascending=False)
totalRevenueMonth

Month
Jan    111778.4115
Mar    104216.3220
Feb     90570.4800
Name: Sales, dtype: float64

In [90]:
totalRevenueDay = df.groupby('Day')['Sales'].sum().sort_values(ascending=False)
totalRevenueDay

Day
15.0    15049.0935
19.0    14883.2355
14.0    13317.2340
27.0    13305.0540
9.0     13103.4750
8.0     12767.3805
2.0     12627.5100
23.0    12262.6560
5.0     12124.8435
3.0     11878.8180
12.0    11421.9735
20.0    10887.6495
25.0    10719.2610
17.0    10418.6145
16.0     9947.3220
10.0     9718.7685
7.0      9679.6350
24.0     9651.4110
11.0     8966.1075
1.0      8863.7745
26.0     8777.0445
28.0     8603.8995
6.0      8351.6265
4.0      7957.6245
30.0     7045.3215
22.0     6620.5965
29.0     5867.6835
21.0     5663.3535
18.0     5569.3365
13.0     5282.4135
31.0     5232.4965
Name: Sales, dtype: float64

In [97]:
# 10- Overall satisfied costumers percentage
df['Satisfied'].mean()

np.float64(0.501)